inherit_from:
  - https://tech.olioex.com/.support/rubocop-styling-v1.0

require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Rails/Delegate:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - lib/janus-ar.rb

Metrics/AbcSize:
  Max: 25
